openapi: 3.0.1
info:
  description: ""
  title: folio
  version: 1.0.0
servers:
- url: /
tags:
- name: golio
paths:
  /articles:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        example: 0
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        example: 10
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: タイトルの検索
        explode: true
        in: query
        name: search_title_text
        required: false
        schema:
          type: string
        style: form
      - description: tagのarray
        example:
        - "[\"tag_1\", \"tag_2\"]"
        explode: true
        in: query
        name: tags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    articles:
                    - id: 記事ID
                      title: 記事タイトル
                      created_at: 作成日
              schema:
                $ref: '#/components/schemas/_articles_get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: ""
              schema:
                $ref: '#/components/schemas/_articles_post_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事投稿
      tags:
      - golio
  /articles/{article_id}:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: 記事ID
                    title: 記事タイトル
                    body: 記事本文
              schema:
                $ref: '#/components/schemas/_articles__article_id__get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事取得
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事更新
      tags:
      - golio
  /articles/{article_id}/ai:
    put:
      deprecated: false
      description: AIに命令を下して、記事の内容の更新をするAPIです
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles__article_id__ai_put_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    generated_body: ""
              schema:
                $ref: '#/components/schemas/_articles__article_id__ai_put_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事AI更新
      tags:
      - golio
  /articles/ai:
    post:
      deprecated: false
      description: AIに命令を下して、記事を作成するAPIです
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              prompt: ut eiusmod enim cillum
            schema:
              $ref: '#/components/schemas/_articles_ai_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    article_id: ""
              schema:
                $ref: '#/components/schemas/_articles_ai_post_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事AI作成
      tags:
      - golio
  /hello:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    hello: world
              schema:
                $ref: '#/components/schemas/_hello_get_200_response'
          description: Success
      security: []
      summary: hello
      tags:
      - golio
  /media:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    total_count: 0
                    media:
                    - id: ""
                      file_type: ""
                      thumbnail_url: ""
                      created_at: ""
                      updated_at: ""
              schema:
                $ref: '#/components/schemas/_media_get_200_response'
          description: Success
      security: []
      summary: メディア一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              file_name: ""
              file_type: ""
            schema:
              $ref: '#/components/schemas/_media_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    upload_presigned_url: ""
              schema:
                $ref: '#/components/schemas/_media_post_200_response'
          description: Success
      security: []
      summary: メディアの登録
      tags:
      - golio
  /media/{medium_id}:
    delete:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: メディアの削除
      tags:
      - golio
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_media__medium_id__get_200_response'
          description: Success
      security: []
      summary: メディアの取得
      tags:
      - golio
  /translation:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_translation_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_translation_post_200_response'
          description: Success
      security: []
      summary: 翻訳
      tags:
      - golio
  /article_tags:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: true
        in: query
        name: search_text
        required: false
        schema:
          type: string
        style: form
      - description: ""
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_article_tags_get_200_response'
          description: Success
      security: []
      summary: 記事タグ一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              name: タグの名前
            schema:
              $ref: '#/components/schemas/_article_tags_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: tag_id
              schema:
                $ref: '#/components/schemas/insert_article_tag_response'
          description: Success
      security: []
      summary: 記事タグの作成
      tags:
      - golio
  /article_tags/{tag_id}:
    delete:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: tag_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/delete_article_tag_response'
          description: Success
      security: []
      summary: 記事タグの削除
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: tag_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              name: new_tag_name
            schema:
              $ref: '#/components/schemas/_article_tags__tag_id__put_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/update_article_tag_response'
          description: Success
      security: []
      summary: 記事タグの更新
      tags:
      - golio
  /english_dictionary/{word}:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: word
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_english_dictionary__word__get_200_response'
          description: Success
      security: []
      summary: 英単語を辞書で引く
      tags:
      - golio
  /english_dictionary/{word}/bookmark:
    delete:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: word
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: 辞書で引いた単語ブックマークを削除
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: word
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: 辞書で引いた単語ブックマークを作成
      tags:
      - golio
  /tasks:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_tasks_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_post_200_response'
          description: Success
      security: []
      summary: タスク作成
      tags:
      - golio
  /tasks/{id}:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_tasks__id__get_200_response'
          description: Success
      security: []
      summary: タスク詳細取得
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_tasks_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_post_200_response'
          description: Success
      security: []
      summary: タスク編集
      tags:
      - golio
components:
  schemas:
    word_definition:
      example:
        examples:
        - examples
        - examples
        synonyms:
        - synonyms
        - synonyms
        part_of_speech: part_of_speech
        antonyms:
        - antonyms
        - antonyms
        definition: definition
      properties:
        definition:
          type: string
        part_of_speech:
          type: string
        synonyms:
          items:
            type: string
          type: array
        antonyms:
          items:
            type: string
          type: array
        examples:
          items:
            type: string
          type: array
      required:
      - antonyms
      - definition
      - examples
      - part_of_speech
      - synonyms
      type: object
    word_detail:
      example:
        word: word
        definitions:
        - examples:
          - examples
          - examples
          synonyms:
          - synonyms
          - synonyms
          part_of_speech: part_of_speech
          antonyms:
          - antonyms
          - antonyms
          definition: definition
        - examples:
          - examples
          - examples
          synonyms:
          - synonyms
          - synonyms
          part_of_speech: part_of_speech
          antonyms:
          - antonyms
          - antonyms
          definition: definition
        frequency: 0.8008281904610115
      properties:
        word:
          type: string
        definitions:
          items:
            $ref: '#/components/schemas/word_definition'
          type: array
        frequency:
          type: number
      required:
      - definitions
      - frequency
      - word
      type: object
    delete_article_tag_response:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    update_article_tag_response:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    insert_article_tag_response:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    language_code:
      enum:
      - auto
      - af
      - sq
      - am
      - ar
      - hy
      - az
      - bn
      - bs
      - bg
      - ca
      - zh
      - zh-TW
      - hr
      - cs
      - da
      - fa-AF
      - nl
      - en
      - et
      - fa
      - tl
      - fi
      - fr
      - fr-CA
      - ka
      - de
      - el
      - gu
      - ht
      - ha
      - he
      - hi
      - hu
      - is
      - id
      - ga
      - it
      - ja
      - kn
      - kk
      - ko
      - lv
      - lt
      - mk
      - ms
      - ml
      - mt
      - mr
      - mn
      - "no"
      - ps
      - pl
      - pt
      - pt-PT
      - pa
      - ro
      - ru
      - sr
      - si
      - sk
      - sl
      - so
      - es
      - es-MX
      - sw
      - sv
      - ta
      - te
      - th
      - tr
      - uk
      - ur
      - uz
      - vi
      - cy
      type: string
    article:
      example:
        created_at: created_at
        id: id
        title: title
        tags:
        - name: name
          id: id
        - name: name
          id: id
      properties:
        id:
          type: string
        title:
          type: string
        created_at:
          type: string
        tags:
          items:
            $ref: '#/components/schemas/article_tag'
          type: array
      required:
      - created_at
      - id
      - tags
      - title
      type: object
    article_tag:
      example:
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
      required:
      - id
      - name
      type: object
    _articles_get_200_response:
      example:
        total: 0
        articles:
        - created_at: created_at
          id: id
          title: title
          tags:
          - name: name
            id: id
          - name: name
            id: id
        - created_at: created_at
          id: id
          title: title
          tags:
          - name: name
            id: id
          - name: name
            id: id
      properties:
        articles:
          items:
            $ref: '#/components/schemas/article'
          type: array
        total:
          type: integer
      required:
      - articles
      - total
      type: object
    _articles_get_400_response:
      example:
        code: 6
        message: message
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    _articles_post_request:
      properties:
        title:
          type: string
        body:
          type: string
        tag_ids:
          items:
            type: string
          type: array
      required:
      - body
      - tag_ids
      - title
      type: object
    _articles_post_200_response:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    _articles__article_id__get_200_response:
      example:
        user_id: user_id
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        title: title
        body: body
        tags:
        - name: name
          id: id
        - name: name
          id: id
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        created_at:
          format: date-time
          type: string
        user_id:
          type: string
        tags:
          items:
            $ref: '#/components/schemas/article_tag'
          type: array
      required:
      - body
      - created_at
      - id
      - tags
      - title
      - user_id
      type: object
    _articles__article_id__ai_put_request:
      properties:
        message:
          description: AIに対する命令のメッセージです
          type: string
      required:
      - message
      type: object
    _articles__article_id__ai_put_200_response:
      example:
        generated_body: generated_body
      properties:
        generated_body:
          type: string
      required:
      - generated_body
      type: object
    _articles_ai_post_request:
      properties:
        prompt:
          description: AIに対する命令のメッセージです
          type: string
      required:
      - prompt
      type: object
    _articles_ai_post_200_response:
      example:
        article_id: article_id
      properties:
        article_id:
          type: string
      required:
      - article_id
      type: object
    _hello_get_200_response:
      example:
        hello: hello
      properties:
        hello:
          type: string
      required:
      - hello
      type: object
    _media_get_200_response_media_inner:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        file_type: file_type
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        thumbnail_url: http://example.com/aeiou
      properties:
        id:
          type: string
        file_type:
          type: string
        thumbnail_url:
          format: url
          nullable: true
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - created_at
      - file_type
      - id
      - updated_at
      type: object
    _media_get_200_response:
      example:
        total_count: 0
        media:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          file_type: file_type
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          thumbnail_url: http://example.com/aeiou
        - updated_at: 2000-01-23T04:56:07.000+00:00
          file_type: file_type
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          thumbnail_url: http://example.com/aeiou
      properties:
        total_count:
          type: integer
        media:
          items:
            $ref: '#/components/schemas/_media_get_200_response_media_inner'
          type: array
      required:
      - media
      - total_count
      type: object
    _media_post_request:
      properties:
        file_name:
          type: string
      required:
      - file_name
      type: object
    _media_post_200_response:
      example:
        upload_presigned_url: upload_presigned_url
      properties:
        upload_presigned_url:
          type: string
      required:
      - upload_presigned_url
      type: object
    _media__medium_id__get_200_response:
      example:
        file_type: file_type
        download_url: download_url
        medium_id: medium_id
        thumbnail_url: thumbnail_url
      properties:
        medium_id:
          type: string
        thumbnail_url:
          type: string
        download_url:
          type: string
        file_type:
          type: string
      required:
      - download_url
      - file_type
      - medium_id
      - thumbnail_url
      type: object
    _translation_post_request:
      properties:
        source_language_code:
          $ref: '#/components/schemas/language_code'
        target_language_code:
          $ref: '#/components/schemas/language_code'
        text:
          description: 翻訳するテキスト
          type: string
      required:
      - source_language_code
      - target_language_code
      - text
      type: object
    _translation_post_200_response:
      example:
        translated_text: translated_text
      properties:
        translated_text:
          description: 翻訳済みテキスト
          type: string
      required:
      - translated_text
      type: object
    _article_tags_get_200_response:
      example:
        tags:
        - name: name
          id: id
        - name: name
          id: id
      properties:
        tags:
          items:
            $ref: '#/components/schemas/article_tag'
          type: array
      required:
      - tags
      type: object
    _article_tags_post_request:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    _article_tags__tag_id__put_request:
      properties:
        name:
          type: string
      required:
      - 01J07SJQZHDHD50P4TDET04P8W
      - name
      type: object
    _english_dictionary__word__get_200_response:
      example:
        origin:
          word: word
          definitions:
          - examples:
            - examples
            - examples
            synonyms:
            - synonyms
            - synonyms
            part_of_speech: part_of_speech
            antonyms:
            - antonyms
            - antonyms
            definition: definition
          - examples:
            - examples
            - examples
            synonyms:
            - synonyms
            - synonyms
            part_of_speech: part_of_speech
            antonyms:
            - antonyms
            - antonyms
            definition: definition
          frequency: 0.8008281904610115
        translated:
          word: word
          definitions:
          - examples:
            - examples
            - examples
            synonyms:
            - synonyms
            - synonyms
            part_of_speech: part_of_speech
            antonyms:
            - antonyms
            - antonyms
            definition: definition
          - examples:
            - examples
            - examples
            synonyms:
            - synonyms
            - synonyms
            part_of_speech: part_of_speech
            antonyms:
            - antonyms
            - antonyms
            definition: definition
          frequency: 0.8008281904610115
      properties:
        origin:
          $ref: '#/components/schemas/word_detail'
        translated:
          $ref: '#/components/schemas/word_detail'
      required:
      - origin
      - translated
      type: object
    _tasks_post_request:
      properties:
        title:
          type: string
        detail:
          type: string
        start_time:
          format: date-time
          nullable: true
          type: string
        due_time:
          format: date-time
          nullable: true
          type: string
      required:
      - detail
      - title
      type: object
    _tasks__id__get_200_response:
      example:
        start_time: 2000-01-23T04:56:07.000+00:00
        due_time: 2000-01-23T04:56:07.000+00:00
        updated_at: 2000-01-23T04:56:07.000+00:00
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        detail: detail
        title: title
      properties:
        id:
          type: string
        title:
          type: string
        detail:
          type: string
        start_time:
          format: date-time
          nullable: true
          type: string
        due_time:
          format: date-time
          nullable: true
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - created_at
      - detail
      - id
      - title
      - updated_at
      type: object
  securitySchemes: {}
